import { useState } from 'react'
import { FileText, Download, Check } from 'lucide-react'
import { useApp } from '../../context/AppContext'
import { formatCurrency, formatDate, formatWeight, formatDistance } from '../../utils/formatters'

export default function ContractGenerator() {
  const { loads, getCarrierById } = useApp()
  const [selectedLoadId, setSelectedLoadId] = useState('')
  const [generated, setGenerated] = useState(false)

  const eligibleLoads = loads.filter(l =>
    ['assigned', 'in-transit', 'delivered'].includes(l.status) && l.assignedCarrierId
  )

  const selectedLoad = loads.find(l => l.id === selectedLoadId)
  const carrier = selectedLoad?.assignedCarrierId
    ? getCarrierById(selectedLoad.assignedCarrierId)
    : null

  const handleGenerate = () => {
    setGenerated(true)
  }

  const handleDownload = () => {
    const contractText = generateContractText(selectedLoad, carrier)
    const blob = new Blob([contractText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `Contract-${selectedLoad.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const generateContractText = (load, carrier) => {
    return `
FREIGHT TRANSPORTATION CONTRACT
================================

Contract Number: CTR-${Date.now()}
Date: ${formatDate(new Date().toISOString())}

SHIPPER INFORMATION
-------------------
Company: ${load.shipperCompany}
Load Reference: ${load.id}

CARRIER INFORMATION
-------------------
Carrier Name: ${carrier?.name || 'N/A'}
MC Number: ${carrier?.mcNumber || 'N/A'}
DOT Number: ${carrier?.dotNumber || 'N/A'}
Contact: ${carrier?.email || 'N/A'}

SHIPMENT DETAILS
----------------
Origin: ${load.origin} ${load.originZip}
Destination: ${load.destination} ${load.destinationZip}
Pickup Date: ${formatDate(load.pickupDate)}
Delivery Date: ${formatDate(load.deliveryDate)}
Equipment Type: ${load.equipmentType}
Weight: ${formatWeight(load.weight)}
Distance: ${formatDistance(load.distance)}
Commodity: ${load.commodity}

Special Instructions:
${load.specialInstructions || 'None'}

RATE CONFIRMATION
-----------------
Agreed Rate: ${formatCurrency(load.rate)}

TERMS AND CONDITIONS
--------------------
1. Carrier agrees to transport the described freight from origin to destination.
2. Carrier shall maintain appropriate insurance coverage throughout transit.
3. Carrier is responsible for any damage to freight during transportation.
4. Payment terms: Net 30 days from delivery.
5. This contract is governed by applicable federal and state transportation laws.

SIGNATURES
----------
Shipper Representative: ___________________________ Date: ___________

Carrier Representative: ___________________________ Date: ___________

---
Generated by FreightCommand Load Broker Portal
    `.trim()
  }

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-text-primary font-heading">Contract Generator</h1>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Selection */}
        <div className="bg-bg-secondary border border-border rounded-xl p-6">
          <h3 className="text-lg font-semibold text-text-primary mb-4">Select Shipment</h3>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-text-secondary mb-2">
                Assigned Shipment
              </label>
              <select
                value={selectedLoadId}
                onChange={(e) => {
                  setSelectedLoadId(e.target.value)
                  setGenerated(false)
                }}
                className="w-full px-4 py-2.5 bg-bg-tertiary border border-border rounded-lg text-text-primary"
              >
                <option value="">Select a shipment...</option>
                {eligibleLoads.map(load => (
                  <option key={load.id} value={load.id}>
                    {load.id} - {load.origin} → {load.destination}
                  </option>
                ))}
              </select>
            </div>

            {selectedLoad && (
              <div className="p-4 bg-bg-tertiary rounded-lg space-y-3">
                <div className="flex justify-between">
                  <span className="text-text-secondary">Shipper</span>
                  <span className="text-text-primary">{selectedLoad.shipperCompany}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-secondary">Carrier</span>
                  <span className="text-text-primary">{carrier?.name || 'N/A'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-secondary">Rate</span>
                  <span className="text-accent-success font-semibold">
                    {formatCurrency(selectedLoad.rate)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-secondary">Equipment</span>
                  <span className="text-text-primary">{selectedLoad.equipmentType}</span>
                </div>
              </div>
            )}

            <button
              onClick={handleGenerate}
              disabled={!selectedLoadId}
              className="w-full py-2.5 bg-accent-primary text-white rounded-lg font-medium hover:bg-accent-primary/90 disabled:opacity-50 transition-colors btn-primary"
            >
              <FileText className="w-5 h-5 inline mr-2" />
              Generate Contract
            </button>
          </div>
        </div>

        {/* Preview */}
        <div className="bg-bg-secondary border border-border rounded-xl p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-text-primary">Contract Preview</h3>
            {generated && (
              <button
                onClick={handleDownload}
                className="flex items-center px-4 py-2 bg-accent-success text-white rounded-lg text-sm font-medium hover:bg-accent-success/90 transition-colors"
              >
                <Download className="w-4 h-4 mr-2" />
                Download
              </button>
            )}
          </div>

          {generated && selectedLoad ? (
            <div className="bg-white text-gray-900 rounded-lg p-6 font-mono text-xs overflow-auto max-h-96">
              <pre className="whitespace-pre-wrap">
                {generateContractText(selectedLoad, carrier)}
              </pre>
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center h-64 text-center">
              <FileText className="w-16 h-16 text-text-muted mb-4" />
              <p className="text-text-secondary">
                Select a shipment and generate a contract to see the preview
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
